### ISSUE TITLE
Erroneous "file not found" upon running 'rails metadata:scan'

### ISSUE THREAD

**Issue by StashUser** [StashApp/StashServer#1]
I have gotten the website up and running without issues by following the guide in README.md. But when I try to populate the database by running **rails metadata:scan**, I encounter a bug telling me that the file that it is trying to process cannot be found.

The file is 100% there. The number of files and the name of the file are correctly identified by the program during scanning, yet it reports on the next line that the file cannot be found. Ultimately, the script fails at the first video file with the error **Failed encoding...** and **Errors: no output file created.**

I've tried to do some troubleshooting but I'm not skilled enough. Could the bug perhaps be similar in nature to [this issue](https://github.com/streamio/streamio-ffmpeg/issues/165) at streamio-ffmpeg?

**Full output from terminal:**
```
user@server:~/src/StashServer$ rails metadata:scan
I, [2017-04-17T22:10:44.157153 #25200]  INFO -- : Starting scan of 487 files
I, [2017-04-17T22:10:44.253758 #25200]  INFO -- : /home/user/.x/videos/CORRECT-TITLE-OF-VIDEO.mp4 not found.  Calculating checksum...
E, [2017-04-17T22:10:44.721037 #25200] ERROR -- : Failed encoding...
["/usr/local/bin/ffmpeg", "-y", "-v", "quiet", "-ss", "98.2842", "-i", "/home/user/.x/videos/CORRECT-TITLE-OF-VIDEO.mp4", "-vframes", "1", "-f", "image2", "-q:v", "5", "-vf", "scale='320:-1'", "/home/user/.x/metadata/screenshots/9b36d390ad03df460540513c841c5757.thumb.jpg"]


Errors: no output file created. 

rails aborted!
FFMPEG::Error: Failed encoding.Errors: no output file created. Full output: 
/var/lib/gems/2.3.0/gems/streamio-ffmpeg-3.0.2/lib/ffmpeg/transcoder.rb:112:in `validate_output_file'
/var/lib/gems/2.3.0/gems/streamio-ffmpeg-3.0.2/lib/ffmpeg/transcoder.rb:45:in `run'
/var/lib/gems/2.3.0/gems/streamio-ffmpeg-3.0.2/lib/ffmpeg/movie.rb:200:in `transcode'
/home/user/src/StashServer/lib/stash_metadata/tasks/scan.rb:72:in `make_screenshot'
/home/user/src/StashServer/lib/stash_metadata/tasks/scan.rb:64:in `make_screenshots'
/home/user/src/StashServer/lib/stash_metadata/tasks/scan.rb:26:in `block in start'
/home/user/src/StashServer/lib/stash_metadata/tasks/scan.rb:9:in `each'
/home/user/src/StashServer/lib/stash_metadata/tasks/scan.rb:9:in `start'
/home/user/src/StashServer/lib/tasks/metadata.rake:15:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/var/lib/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/var/lib/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/var/lib/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
/home/user/src/StashServer/bin/rails:9:in `require'
/home/user/src/StashServer/bin/rails:9:in `<top (required)>'
/var/lib/gems/2.3.0/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `load'
/var/lib/gems/2.3.0/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `call'
/var/lib/gems/2.3.0/gems/spring-2.0.1/lib/spring/client/command.rb:7:in `call'
/var/lib/gems/2.3.0/gems/spring-2.0.1/lib/spring/client.rb:30:in `run'
/var/lib/gems/2.3.0/gems/spring-2.0.1/bin/spring:49:in `<top (required)>'
/var/lib/gems/2.3.0/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `load'
/var/lib/gems/2.3.0/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `<top (required)>'
/home/user/src/StashServer/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => metadata:scan
(See full trace by running task with --trace)
user@server:~/src/StashServer$
```

Notice line 2 after running the scan command. It correctly identifies the file before giving an error that it is not found.

EDIT
I see from line 22 of [/lib/stash_metadata/tasks/scan.rb](https://github.com/StashApp/StashServer/blob/master/lib/stash_metadata/tasks/scan.rb) that this is the intended message for vidoes where the checksum hasn't been calculated before. I wonder what part failed in my case then because it aborts before any of the other messages are printed to the screen?

**Comment by StashUser** [comment]
Fixed by manually creating the folder /metadata/screenshots/ (after running the ffmpeg command manually with verbose output, an error was given to this effect).

**Comment by StashAppDev** [comment]
I'm going to reopen this as this is a bug related to the scraper.  It should be creating these folders if they don't already exist.
